# Generated by Django 2.2.4 on 2019-09-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cuenta_act', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('name_act', models.CharField(max_length=70, verbose_name='Nombre de la Actividad')),
            ],
            options={
                'ordering': ['centro_costo'],
            },
        ),
        migrations.CreateModel(
            name='arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arri', models.CharField(max_length=11, verbose_name='NIT')),
                ('name_arri', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('reten', models.FloatField(default=0, null=True, verbose_name='Retencion')),
                ('tel_arri', models.CharField(max_length=12, verbose_name='Telefono')),
                ('dir_arri', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail_arri', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('fechafact_arri', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='centro_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centro_costo', models.CharField(max_length=20, verbose_name='Número de Cuenta')),
                ('name_ccos', models.CharField(max_length=100, verbose_name='Nombre del Centro de Costo')),
            ],
        ),
        migrations.CreateModel(
            name='cpp_arriendo_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_arriendo', models.CharField(max_length=100, null=True, verbose_name='N° Factura')),
                ('centro_costo', models.CharField(max_length=100, null=True, verbose_name='Centro de Costo')),
                ('inductor_arri', models.FloatField(default=0, verbose_name='Inductor')),
                ('num_cuenta', models.CharField(max_length=100, null=True, verbose_name='Número de Cuenta')),
                ('valor_cpp_arri_detal', models.FloatField(default=0, verbose_name='Valor')),
                ('fecha_cpp_arri_detal', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='cpp_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cpp_prov', models.FloatField(default=0, null=True, verbose_name='Valor')),
                ('fecha_cpp_prov', models.DateField(null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='cpp_servicio_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sm', models.FloatField(default=0, verbose_name='Valor')),
                ('fecha_cpp_sm', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esp', models.CharField(max_length=11, verbose_name='Identificación')),
                ('name_esp', models.CharField(max_length=50, verbose_name='Nombre del Especialista')),
                ('apellidos_esp', models.CharField(max_length=70, verbose_name='Apellidos del Especialista')),
                ('cargo_esp', models.CharField(max_length=70, verbose_name='Cargo del Especialista')),
                ('valor', models.FloatField(default=0, null=True, verbose_name='Monto Devengado al mes')),
                ('reten', models.FloatField(default=0, null=True, verbose_name='Retención')),
                ('tel_esp', models.CharField(max_length=12, verbose_name='Telefono')),
                ('dir_esp', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail_esp', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('fechafact_esp', models.DateField(verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='fac_especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0, null=True)),
                ('fechafac_esp', models.DateField(verbose_name='Fecha')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.especialista', verbose_name='Identificación')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_prov', models.CharField(max_length=11, null=True, verbose_name='NIT')),
                ('name_prov', models.CharField(max_length=100, verbose_name='Nombre del Proveedor')),
                ('name_servp', models.CharField(max_length=100, null=True, verbose_name='Nombre del Servicio-Producto')),
                ('dir_prov', models.CharField(max_length=100, verbose_name='Dirección')),
                ('tel_prov', models.CharField(max_length=12, verbose_name='Telefono')),
                ('mail_prov', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('fecharegistro_prov', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='servicio_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_sgen', models.CharField(max_length=11, verbose_name='NIT')),
                ('name_sgen', models.CharField(max_length=100, verbose_name='Nombre el la Empresa')),
                ('tel_sgen', models.CharField(max_length=12, verbose_name='Telefono')),
                ('dir_sgen', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail_sgen', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('fechafact_sgen', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='servicio_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_servm', models.CharField(max_length=11, verbose_name='NIT')),
                ('name_servm', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('tel_servm', models.CharField(max_length=12, verbose_name='Telefono')),
                ('dir_servm', models.CharField(max_length=100, verbose_name='Dirección')),
                ('mail_servm', models.EmailField(max_length=60, verbose_name='E-mail')),
                ('fechafact_servm', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fact', models.CharField(max_length=20, verbose_name='Nombre del Tipo de Facturación')),
            ],
        ),
        migrations.CreateModel(
            name='sub_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subactivity', models.CharField(max_length=70, verbose_name='Nombre de Actividad')),
                ('valor_sa', models.FloatField(default=0, null=True, verbose_name='Valor ISS')),
                ('pct', models.FloatField(default=0.25, null=True, verbose_name='Porcentaje ISS Adicional')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.actividad', verbose_name='ID actividad')),
            ],
            options={
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='inductor_arri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('induc', models.FloatField(verbose_name='Inductor')),
                ('fecha_induc', models.DateField(null=True, verbose_name='Fecha de Actualizacion')),
                ('arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.arriendo', verbose_name='Nombre del Ente')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro Costo')),
            ],
        ),
        migrations.CreateModel(
            name='fac_especialista_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0, null=True)),
                ('fechafac_detalle', models.DateField(null=True, verbose_name='Fecha')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.actividad', verbose_name='Actividad')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo')),
                ('fac_especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.fac_especialista', verbose_name='Codigo de la Factura')),
                ('sub_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.sub_activity', verbose_name='Subactividad')),
                ('tipo_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.tipo_fact', verbose_name='Tipo de Factura o CPP')),
            ],
        ),
        migrations.CreateModel(
            name='especialista_cpp_aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.especialista', verbose_name='Identificación Especialista')),
                ('tipo_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.tipo_fact', verbose_name='Tipo Facturacion')),
            ],
        ),
        migrations.CreateModel(
            name='cpp_servicio_medico_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sm_detalle', models.FloatField(null=True)),
                ('fecha_sm_detalle', models.DateField(null=True, verbose_name='Fecha')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.actividad', verbose_name='Actividad')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Cuenta Centro de Costo')),
                ('cpp_servicio_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.cpp_servicio_medico', verbose_name='Codigo Servicio Medico')),
                ('sub_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.sub_activity', verbose_name='Subactividad')),
            ],
        ),
        migrations.AddField(
            model_name='cpp_servicio_medico',
            name='servicio_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.servicio_medico', verbose_name='Nit Servicio Medico'),
        ),
        migrations.CreateModel(
            name='cpp_proveedor_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True, verbose_name='Valor')),
                ('fecha_cpp_prov_detal', models.DateField(null=True, verbose_name='Fecha')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo')),
                ('cpp_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.cpp_proveedor', verbose_name='N° de Factura')),
            ],
        ),
        migrations.AddField(
            model_name='cpp_proveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor', verbose_name='Nit del Proveedor'),
        ),
        migrations.CreateModel(
            name='cpp_arriendo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cpp_arri', models.FloatField(default=0, null=True, verbose_name='Valor de la Factura')),
                ('valor_cont', models.FloatField(default=0, null=True, verbose_name='Valor Contabilizado')),
                ('fecha_cpp_arri', models.DateField(null=True, verbose_name='Fecha')),
                ('arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.arriendo', verbose_name='Nit Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo'),
        ),
    ]
