# Generated by Django 2.2.4 on 2019-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_arriendo_detalle',
            name='cpp_arriendo',
            field=models.IntegerField(max_length=100, null=True, verbose_name='N° Factura'),
        ),
    ]
