# Generated by Django 2.2.4 on 2019-09-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20190910_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_arriendo_detalle',
            name='cpp_arriendo',
        ),
    ]
