# Generated by Django 2.2.4 on 2019-09-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_auto_20190911_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retencion en %'),
        ),
    ]
