# Generated by Django 2.2.4 on 2019-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_auto_20190911_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductor_arri',
            name='induc',
            field=models.FloatField(verbose_name='Inductor en %'),
        ),
    ]
