# Generated by Django 2.2.4 on 2019-09-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_auto_20190916_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social_reglament', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Opción')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.especialista', verbose_name='Nombre del Especialista')),
            ],
        ),
    ]
