# Generated by Django 2.2.4 on 2019-09-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_auto_20190916_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dependiente_cargo',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Dependiente a Cargo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pension_obligado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Obligado a Cotizar Pension '),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reten_10',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Retención del 10%'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reten_11',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Retención 11%'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='reten_art_383',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Aplica Retención Art. 383'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razon_social_reglament',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=5, verbose_name='Razon Social Reglamentaria'),
        ),
    ]
