# Generated by Django 2.2.4 on 2019-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_auto_20190916_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='uvt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_uvt', models.FloatField(default=0, null=True, verbose_name='Valor del UVT')),
            ],
        ),
    ]
