# Generated by Django 2.2.4 on 2019-09-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_uvt'),
    ]

    operations = [
        migrations.CreateModel(
            name='reten_383',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo', models.FloatField(default=0, null=True, verbose_name='Minimo')),
                ('maximo', models.FloatField(default=0, null=True, verbose_name='Máximo')),
                ('porcent', models.FloatField(default=0, null=True, verbose_name='Porcentaje')),
                ('adicion', models.FloatField(default=0, null=True, verbose_name='Adicion Puntos')),
            ],
        ),
        migrations.AddField(
            model_name='uvt',
            name='restric_smlv',
            field=models.FloatField(default=0, null=True, verbose_name='Restricción SMLV'),
        ),
        migrations.AddField(
            model_name='uvt',
            name='smlv',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Salario Minimo'),
        ),
    ]
