# Generated by Django 2.2.4 on 2019-09-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_auto_20190917_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='cargo_esp',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='reten',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='valor',
        ),
        migrations.AddField(
            model_name='contrato',
            name='cargo_esp',
            field=models.CharField(max_length=70, null=True, verbose_name='Cargo del Especialista'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor',
            field=models.FloatField(default=0, null=True, verbose_name='Monto Devengado al mes'),
        ),
    ]
