# Generated by Django 2.2.4 on 2019-09-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_auto_20190920_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='comp_salud_art',
            field=models.FloatField(default=0, null=True, verbose_name='Indemnizaciones Laborales'),
        ),
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='int_pre_vivi',
            field=models.FloatField(default=0, null=True, verbose_name='Intereses Prestamo de Vivienda Max 100 UVT '),
        ),
        migrations.AlterField(
            model_name='fac_especialista_detalle',
            name='aport_volun_pension',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes Voluntarios a Pension Max 25% S.'),
        ),
    ]
