# Generated by Django 2.2.4 on 2019-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_auto_20190920_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fac_especialista_detalle',
            old_name='comp_salud_art',
            new_name='indem_lab',
        ),
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='aport_afc',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes a Cuentas AFC'),
        ),
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='aport_volun_emple',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes Voluntarios del Empleador'),
        ),
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='plan_comp_salud',
            field=models.FloatField(default=0, null=True, verbose_name='Plan Complementrio de Salud '),
        ),
    ]
