# Generated by Django 2.2.4 on 2019-09-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_auto_20190920_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='centro_actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=20, verbose_name='N° Cuenta')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.actividad', verbose_name='Actividad')),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo')),
            ],
        ),
    ]
