# Generated by Django 2.2.4 on 2019-09-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0026_centro_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['name_act']},
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='centro_costo',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='sub_activity',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='sub_activity',
            name='pct',
        ),
        migrations.RemoveField(
            model_name='sub_activity',
            name='valor_sa',
        ),
        migrations.AddField(
            model_name='actividad',
            name='sub_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.sub_activity', verbose_name='Grupo de la Actividad'),
        ),
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='centro_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_actividad', verbose_name='Actividad'),
        ),
    ]
