# Generated by Django 2.2.4 on 2019-09-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0027_auto_20190923_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_activity',
            options={'ordering': ['name_subactivity']},
        ),
    ]
