# Generated by Django 2.2.4 on 2019-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0028_auto_20190923_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='uvt',
            name='retencion',
            field=models.FloatField(default=11, null=True, verbose_name='Retención'),
        ),
        migrations.AlterField(
            model_name='uvt',
            name='smlv',
            field=models.FloatField(default=828116, null=True, verbose_name='Valor Salario Minimo'),
        ),
        migrations.AlterField(
            model_name='uvt',
            name='valor_uvt',
            field=models.FloatField(default=34270, null=True, verbose_name='Valor del UVT'),
        ),
    ]
