# Generated by Django 2.2.4 on 2019-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_auto_20190923_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='costo',
            field=models.FloatField(default=0, null=True, verbose_name='Costo Actividad'),
        ),
    ]
