# Generated by Django 2.2.4 on 2019-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0030_actividad_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='pct_iss',
            field=models.FloatField(default=0.25, null=True, verbose_name='Porcentaje ISS Adicional'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='valor_iss',
            field=models.FloatField(default=0, null=True, verbose_name='Valor ISS'),
        ),
    ]
