# Generated by Django 2.2.4 on 2019-09-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_auto_20190923_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista_cpp_aux',
            name='especialista',
        ),
        migrations.AddField(
            model_name='especialista_cpp_aux',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato', verbose_name='Identificación Especialista'),
        ),
    ]
