# Generated by Django 2.2.4 on 2019-09-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_auto_20190923_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_especialista_detalle',
            name='centro_actividad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_actividad', verbose_name='Actividad'),
        ),
    ]
