# Generated by Django 2.2.4 on 2019-09-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0038_auto_20190923_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='sub_activity',
        ),
    ]
