# Generated by Django 2.2.4 on 2019-09-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0039_remove_fac_especialista_detalle_sub_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='id_cuenta_act',
        ),
    ]
