# Generated by Django 2.2.4 on 2019-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0040_auto_20190923_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='glosa',
            field=models.FloatField(default=0, null=True, verbose_name='Glosa del mes'),
        ),
    ]
