# Generated by Django 2.2.4 on 2019-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0042_auto_20190925_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='glosa',
        ),
        migrations.AddField(
            model_name='retencion',
            name='glosa',
            field=models.FloatField(default=0, null=True, verbose_name='Glosa del mes'),
        ),
    ]
