# Generated by Django 2.2.4 on 2019-10-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0043_auto_20190925_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='fac_especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.fac_especialista', verbose_name='Factura'),
        ),
    ]
