# Generated by Django 2.2.4 on 2019-10-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0044_retencion_fac_especialista'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_especialista',
            name='acum',
            field=models.FloatField(default=0, null=True),
        ),
    ]
