# Generated by Django 2.2.4 on 2019-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0045_fac_especialista_acum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='fac_especialista',
            field=models.FloatField(default=0, null=True, verbose_name='Factura'),
        ),
    ]
