# Generated by Django 2.2.4 on 2019-10-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0050_opcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='opcion',
        ),
        migrations.AddField(
            model_name='uvt',
            name='name',
            field=models.CharField(max_length=51, null=True, verbose_name='Nombre Tarifa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dependiente_cargo',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Dependiente a Cargo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pension_obligado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Obligado a Cotizar Pension '),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razon_social_reglament',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Razon Social Reglamentaria'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='reten_10',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Retención del 10%'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='reten_11',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Retención 11%'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='reten_art_383',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='Aplica Retención Art. 383'),
        ),
    ]
