# Generated by Django 2.2.4 on 2019-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0052_fac_especialista_uvt'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='name_especialista',
            field=models.IntegerField(default=0, null=True, verbose_name='Nombre Especialista'),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='fac_especialista',
            field=models.IntegerField(default=0, null=True, verbose_name='Códido Especialista'),
        ),
    ]
