# Generated by Django 2.2.4 on 2019-10-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0055_auto_20191019_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uvt',
            name='retencion',
        ),
    ]
