# Generated by Django 2.2.4 on 2019-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0056_remove_uvt_retencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='aport_afc',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='aport_volun_emple',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='aport_volun_pension',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='indem_lab',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='int_pre_vivi',
        ),
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='plan_comp_salud',
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='aport_afc',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes a Cuentas AFC'),
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='aport_volun_emple',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes Voluntarios del Empleador'),
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='aport_volun_pension',
            field=models.FloatField(default=0, null=True, verbose_name='Aportes Voluntarios a Pension Max 25% S.'),
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='indem_lab',
            field=models.FloatField(default=0, null=True, verbose_name='Indemnizaciones Laborales'),
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='int_pre_vivi',
            field=models.FloatField(default=0, null=True, verbose_name='Intereses Prestamo de Vivienda Max 100 UVT '),
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='plan_comp_salud',
            field=models.FloatField(default=0, null=True, verbose_name='Plan Complementrio de Salud '),
        ),
    ]
