# Generated by Django 2.2.4 on 2019-10-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0057_auto_20191019_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='aport_cuenta_afc',
            field=models.FloatField(default=0, null=True, verbose_name='Aporte Renta Exenta'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='aport_volun_empleador',
            field=models.FloatField(default=0, null=True, verbose_name='Aporte Voluntario Empleador'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='indemni_lab',
            field=models.FloatField(default=0, null=True, verbose_name='Indemnizaciones Laborales'),
        ),
    ]
