# Generated by Django 2.2.4 on 2019-10-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0059_fac_especialista_rent_exten_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_especialista',
            name='top_deduc_rent_exte',
            field=models.FloatField(default=25, null=True, verbose_name='Tope Deducciones + Renta Extensa '),
        ),
        migrations.AddField(
            model_name='retencion',
            name='re_fuente_uvt',
            field=models.FloatField(default=0, null=True, verbose_name='Retenccion en la Fuente Expresada en UVT'),
        ),
    ]
