# Generated by Django 2.2.4 on 2019-10-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0060_auto_20191021_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_especialista',
            name='top_deduc_rent_exte',
            field=models.FloatField(default=40, null=True, verbose_name='Tope Deducciones + Renta Extensa '),
        ),
    ]
