# Generated by Django 2.2.4 on 2019-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0061_auto_20191021_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='reten_383',
            name='resta',
            field=models.FloatField(default=0, null=True, verbose_name='Resta'),
        ),
    ]
