# Generated by Django 2.2.4 on 2019-10-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0063_auto_20191021_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='re_tope_rent_exent_lab',
            field=models.FloatField(default=0, null=True, verbose_name='Tope Deducciones + Renta Exenta'),
        ),
        migrations.AlterField(
            model_name='retencion',
            name='re_rent_exent_lab',
            field=models.FloatField(default=0, null=True, verbose_name='Renta Exenta Laboral'),
        ),
    ]
