# Generated by Django 2.2.4 on 2019-10-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0064_auto_20191021_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='centro_actividad',
        ),
    ]
