# Generated by Django 2.2.4 on 2019-10-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0066_fac_especialista_detalle_centro_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_actividad',
            name='cuenta',
            field=models.IntegerField(max_length=20, verbose_name='N° Cuenta'),
        ),
    ]
