# Generated by Django 2.2.4 on 2019-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0067_auto_20191029_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_actividad',
            name='cuenta',
            field=models.IntegerField(null=True, verbose_name='N° Cuenta'),
        ),
    ]
