# Generated by Django 2.2.4 on 2019-10-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0068_auto_20191029_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='centro_actividad',
        ),
    ]
