# Generated by Django 2.2.4 on 2019-10-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0069_remove_fac_especialista_detalle_centro_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_especialista_detalle',
            name='centro_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_actividad', verbose_name='Actividad'),
        ),
    ]
