# Generated by Django 2.2.4 on 2019-10-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0070_fac_especialista_detalle_centro_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro_actividad',
            name='cuenta',
            field=models.BigIntegerField(null=True, verbose_name='N° Cuenta'),
        ),
    ]
