# Generated by Django 2.2.4 on 2019-11-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0071_auto_20191031_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta_reten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cuenta', models.CharField(max_length=50, verbose_name='Nombre de Cuenta')),
                ('num_cuenta', models.BigIntegerField(null=True, verbose_name='Número de Cuenta')),
            ],
        ),
    ]
