# Generated by Django 2.2.4 on 2019-11-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0072_cuenta_reten'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_reten',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.contrato', verbose_name='Contrato-Especialista'),
        ),
    ]
