# Generated by Django 2.2.4 on 2019-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0073_cuenta_reten_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre del Contrato'),
        ),
    ]
