# Generated by Django 2.2.4 on 2019-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0074_contrato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nombre',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre de la Base'),
        ),
    ]
