# Generated by Django 2.2.4 on 2019-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0075_auto_20191119_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
