# Generated by Django 2.2.4 on 2019-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0076_contrato_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta_reten',
            name='porc_retencion',
            field=models.FloatField(null=True, verbose_name='Retención'),
        ),
    ]
