# Generated by Django 2.2.4 on 2019-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0077_cuenta_reten_porc_retencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_reten',
            name='porc_retencion',
            field=models.FloatField(default=4, null=True, verbose_name='Retención en %'),
        ),
    ]
