# Generated by Django 2.2.4 on 2019-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0081_auto_20191119_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='cuenta_reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retencion en %'),
        ),
    ]
