# Generated by Django 2.2.4 on 2019-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0082_arriendo_cuenta_reten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cuenta_reten',
            field=models.CharField(default=0, max_length=60, null=True, verbose_name='Cuenta Retenedora'),
        ),
    ]
