# Generated by Django 2.2.4 on 2019-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0083_auto_20191227_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cuenta_reten',
            field=models.CharField(max_length=60, null=True, verbose_name='Cuenta Retenedora'),
        ),
    ]
