# Generated by Django 2.2.4 on 2019-12-30 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0085_cpp_arriendo_detalle_cuenta_reten'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta_reten',
            field=models.CharField(max_length=20, null=True, verbose_name='Cuenta Retenedora'),
        ),
        migrations.CreateModel(
            name='Inductor_prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
