# Generated by Django 2.2.4 on 2019-12-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0086_auto_20191230_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retención en %'),
        ),
    ]
