# Generated by Django 2.2.4 on 2019-12-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0087_proveedor_reten'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, null=True, verbose_name='Nombre del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.CharField(max_length=70, null=True, verbose_name='Nombre de la Cuenta')),
                ('cuenta', models.CharField(max_length=20, null=True, verbose_name='Número de Cuenta')),
                ('centro_costo', models.CharField(max_length=70, null=True, verbose_name='Nombre del Producto')),
                ('distrib', models.FloatField(default=0, null=True, verbose_name='% Distribución')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, null=True, verbose_name='Nombre del Producto')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Inductor_prov',
        ),
        migrations.AddField(
            model_name='distribucion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor', verbose_name='Proveedor'),
        ),
    ]
