# Generated by Django 2.2.4 on 2020-01-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0090_proveedor_meneja_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo'),
        ),
    ]
