# Generated by Django 2.2.4 on 2020-01-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0092_proveedor_distri_fija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='name_servp',
        ),
    ]
