# Generated by Django 2.2.4 on 2020-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0093_remove_proveedor_name_servp'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='naturaleza_cuenta',
            field=models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], default='Debito', max_length=8, verbose_name='Naturaleza de la Cuenta'),
        ),
    ]
