# Generated by Django 2.2.4 on 2020-01-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0094_distribucion_naturaleza_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='valor',
        ),
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='cant_produc',
            field=models.FloatField(null=True, verbose_name='Cantidad Producto'),
        ),
        migrations.AlterField(
            model_name='cpp_proveedor_detalle',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.centro_costo', verbose_name='Centro de Costo'),
        ),
    ]
