# Generated by Django 2.2.4 on 2020-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0095_auto_20200103_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='cant_produc',
        ),
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Valor'),
        ),
    ]
