# Generated by Django 2.2.4 on 2020-01-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0097_auto_20200103_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='valor',
        ),
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='cant_produc',
            field=models.FloatField(default=0, null=True, verbose_name='Cantidad Productos'),
        ),
    ]
