# Generated by Django 2.2.4 on 2020-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0098_auto_20200103_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='cant_flete',
            field=models.FloatField(default=0, null=True, verbose_name='Cantidad Flete'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='valor_flete',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Flete'),
        ),
    ]
