# Generated by Django 2.2.4 on 2020-01-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0100_cpp_proveedor_detalle_distribucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='meneja_iva',
        ),
        migrations.AddField(
            model_name='producto',
            name='meneja_iva',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='¿Maneja Iva?'),
        ),
    ]
