# Generated by Django 2.2.4 on 2020-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0101_auto_20200103_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor',
            name='aire_medicinal',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='¿corresponde a arriendo de aire medicinal?'),
        ),
    ]
