# Generated by Django 2.2.4 on 2020-01-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0102_cpp_proveedor_aire_medicinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor',
            name='aire_medicinal',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿corresponde a arriendo de aire medicinal?'),
        ),
    ]
