# Generated by Django 2.2.4 on 2020-01-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0103_auto_20200103_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpp_proveedor_subdetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_proveedor', models.IntegerField(null=True, verbose_name='N° de Factura')),
                ('centro_costo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Centro de Costo')),
                ('distribucion', models.FloatField(default=0, null=True, verbose_name='Distribución')),
                ('cant_produc', models.FloatField(default=0, null=True, verbose_name='Cantidad Productos')),
                ('cant_flete', models.FloatField(default=0, null=True, verbose_name='Cantidad Flete')),
                ('valor_flete', models.FloatField(default=0, null=True, verbose_name='Valor Flete')),
                ('fecha_cpp_prov_detal', models.DateField(null=True, verbose_name='Fecha')),
            ],
        ),
    ]
