# Generated by Django 2.2.4 on 2020-01-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0105_auto_20200103_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='cuenta',
            field=models.CharField(max_length=20, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='distrib',
            field=models.FloatField(default=0, null=True, verbose_name='% Distribución'),
        ),
    ]
