# Generated by Django 2.2.4 on 2020-01-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0106_auto_20200103_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='naturaleza_cuenta',
            field=models.CharField(max_length=8, null=True, verbose_name='Naturaleza de la Cuenta'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='nombre_cuenta',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre de la Cuenta'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='proveedor',
            field=models.IntegerField(null=True, verbose_name='Nit del Proveedor'),
        ),
    ]
