# Generated by Django 2.2.4 on 2020-01-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0107_auto_20200103_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor_subdetalle',
            name='cpp_proveedor',
            field=models.IntegerField(default=0, null=True, verbose_name='N° de CPP'),
        ),
    ]
