# Generated by Django 2.2.4 on 2020-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0108_auto_20200103_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='meneja_iva',
        ),
        migrations.AddField(
            model_name='distribucion',
            name='cuenta_iva',
            field=models.FloatField(default=0, null=True, verbose_name='Porcentaje Iva'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='meneja_iva',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, verbose_name='¿Maneja Iva?'),
        ),
    ]
