# Generated by Django 2.2.4 on 2020-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0109_auto_20200104_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='valor_iva',
            field=models.FloatField(default=0, null=True, verbose_name='Porcentaje Iva'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='cuenta_iva',
            field=models.CharField(max_length=20, null=True, verbose_name='Numero Cuenta de Iva'),
        ),
    ]
