# Generated by Django 2.2.4 on 2020-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0110_auto_20200104_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='meneja_iva',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2, null=True, verbose_name='¿Maneja Iva?'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='naturaleza_cuenta',
            field=models.CharField(choices=[('Credito', 'Credito')], default='Debito', max_length=8, verbose_name='Naturaleza de la Cuenta'),
        ),
    ]
