# Generated by Django 2.2.4 on 2020-01-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0111_auto_20200107_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='cuenta_iva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero Cuenta de Iva'),
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='valor_iva',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Porcentaje Iva'),
        ),
    ]
