# Generated by Django 2.2.4 on 2020-01-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0112_auto_20200107_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre']},
        ),
    ]
