# Generated by Django 2.2.4 on 2020-01-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0113_auto_20200107_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='distribucion',
        ),
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.producto', verbose_name='Producto'),
        ),
    ]
