# Generated by Django 2.2.4 on 2020-01-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0115_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_subdetalle',
            name='distribucion',
        ),
    ]
