# Generated by Django 2.2.4 on 2020-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0116_remove_cpp_proveedor_subdetalle_distribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='costo',
            field=models.FloatField(default=0, null=True, verbose_name='Costo'),
        ),
    ]
