# Generated by Django 2.2.4 on 2020-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0117_cpp_proveedor_subdetalle_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='name_centro_costo',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre Centro Costo'),
        ),
    ]
