# Generated by Django 2.2.4 on 2020-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0118_cpp_proveedor_subdetalle_name_centro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='valor_produc',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Valor del Producto'),
        ),
    ]
