# Generated by Django 2.2.4 on 2020-01-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0119_cpp_proveedor_detalle_valor_produc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_detalle',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.categoria', verbose_name='Categoria'),
        ),
    ]
