# Generated by Django 2.2.4 on 2020-01-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0120_cpp_proveedor_detalle_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='categoria',
        ),
    ]
