# Generated by Django 2.2.4 on 2020-01-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0121_remove_cpp_proveedor_detalle_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpp_proveedor',
            options={'ordering': ['-id']},
        ),
    ]
