# Generated by Django 2.2.4 on 2020-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0122_auto_20200110_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='cuenta_iva',
            field=models.CharField(max_length=20, null=True, verbose_name='Cuenta Iva'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='valor_iva',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Iva'),
        ),
    ]
