# Generated by Django 2.2.4 on 2020-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0123_auto_20200111_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucion',
            name='naturaleza_cuenta',
            field=models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito')], default='Credito', max_length=8, verbose_name='Naturaleza de la Cuenta'),
        ),
    ]
