# Generated by Django 2.2.4 on 2020-01-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0124_auto_20200111_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas_aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50, null=True, verbose_name='Escriba Numero Cuenta')),
                ('name_cuenta', models.CharField(max_length=50, null=True, verbose_name='Nombre de la Cuenta')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.proveedor', verbose_name='Seleccionar Proveedor')),
            ],
        ),
    ]
