# Generated by Django 2.2.4 on 2020-01-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0125_cuentas_aux'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cuentas_aux',
            new_name='cuenta_aux',
        ),
    ]
