# Generated by Django 2.2.4 on 2020-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0126_auto_20200113_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='name_cuenta_contra',
            field=models.FloatField(default=0, null=True, verbose_name='Cuenta Contra'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='numero_cuenta_contra',
            field=models.CharField(max_length=70, null=True, verbose_name='Nombre Cuenta Contra'),
        ),
        migrations.AddField(
            model_name='cpp_proveedor_subdetalle',
            name='valor_cuenta_contra',
            field=models.FloatField(default=0, null=True, verbose_name='valor Cuenta Contra'),
        ),
    ]
