# Generated by Django 2.2.4 on 2020-01-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0127_auto_20200113_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor_subdetalle',
            name='name_cuenta_contra',
            field=models.CharField(max_length=70, null=True, verbose_name='Cuenta Contra'),
        ),
    ]
