# Generated by Django 2.2.4 on 2020-01-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0129_cuenta_aux_naturaleza_cuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_subdetalle',
            name='name_cuenta_contra',
        ),
        migrations.RemoveField(
            model_name='cpp_proveedor_subdetalle',
            name='numero_cuenta_contra',
        ),
    ]
