# Generated by Django 2.2.4 on 2020-01-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0131_cpp_proveedor_reten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor',
            name='reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retención'),
        ),
    ]
