# Generated by Django 2.2.4 on 2020-01-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0133_auto_20200122_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpp_servi_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpp_serv_public', models.IntegerField(null=True, verbose_name='ID servicio')),
                ('id_serv_public', models.IntegerField(null=True, verbose_name='ID Servicio Público')),
                ('name_serv_public', models.CharField(max_length=50, null=True, verbose_name='Nombre del Tercero')),
                ('id_centro_costo', models.IntegerField(null=True, verbose_name='ID Centro Costo')),
                ('name_ccos', models.CharField(max_length=50, null=True, verbose_name='Nombre Centro de Costo')),
                ('distri', models.FloatField(default=0, null=True, verbose_name='Disctribución (%)')),
                ('name_cuenta_aux', models.CharField(max_length=50, null=True, verbose_name='Nombre Cuenta')),
                ('num_cuenta_aux', models.CharField(max_length=20, null=True, verbose_name='Número Cuenta')),
                ('costo', models.FloatField(default=0, null=True, verbose_name='Costo Asignado')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha')),
            ],
        ),
    ]
