# Generated by Django 2.2.4 on 2020-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0135_auto_20200122_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_servi_detalle',
            name='cpp_serv_public',
            field=models.IntegerField(null=True, verbose_name='ID CPP'),
        ),
    ]
