# Generated by Django 2.2.4 on 2020-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0139_auto_20200219_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='distri_serv_public',
            name='cuenta_iva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta de Iva'),
        ),
        migrations.AddField(
            model_name='distri_serv_public',
            name='num_cuenta_iva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Num. Cuenta de Iva'),
        ),
    ]
