# Generated by Django 2.2.4 on 2020-02-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0140_auto_20200219_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distri_serv_public',
            name='boolean',
        ),
    ]
