# Generated by Django 2.2.4 on 2020-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0141_remove_distri_serv_public_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_servi_detalle',
            name='num_cuenta_iva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Num. Cuenta de Iva'),
        ),
        migrations.AddField(
            model_name='cpp_servi_detalle',
            name='valor_iva',
            field=models.FloatField(default=0, null=True, verbose_name='Valor del Iva'),
        ),
    ]
