# Generated by Django 2.2.4 on 2020-02-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0143_cpp_serv_public_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_serv_public',
            name='iva',
            field=models.FloatField(default=19, null=True, verbose_name='% Iva'),
        ),
    ]
