# Generated by Django 2.2.4 on 2020-02-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0144_auto_20200219_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_serv_public',
            name='total',
            field=models.FloatField(default=0, null=True, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='cpp_serv_public',
            name='costo',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Factura'),
        ),
    ]
