# Generated by Django 2.2.4 on 2020-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0145_auto_20200219_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_serv_public',
            name='iva',
            field=models.FloatField(default=0, null=True, verbose_name='% Iva'),
        ),
    ]
