# Generated by Django 2.2.4 on 2020-02-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0146_auto_20200219_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_servi_detalle',
            name='valor_contra',
            field=models.FloatField(default=0, null=True, verbose_name='Valor Contra'),
        ),
    ]
