# Generated by Django 2.2.4 on 2020-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0147_cpp_servi_detalle_valor_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_serv_public',
            name='reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retención'),
        ),
    ]
