# Generated by Django 2.2.4 on 2020-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0149_categoria_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=70, null=True, verbose_name='Tipo de Servicio')),
                ('descrip', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
    ]
