# Generated by Django 2.2.4 on 2020-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0153_auto_20200224_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='cuenta_reten',
            field=models.CharField(max_length=60, null=True, verbose_name='Cuenta de Retención'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='dir_arri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='mail_arri',
            field=models.EmailField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='name_arri',
            field=models.CharField(max_length=100, verbose_name='Nombre del Tercero'),
        ),
    ]
