# Generated by Django 2.2.4 on 2020-03-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0154_auto_20200302_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductor_arri',
            name='arriendo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.arriendo', verbose_name='Nombre del Tercero'),
        ),
        migrations.AlterField(
            model_name='inductor_arri',
            name='cuenta_especific',
            field=models.CharField(max_length=20, null=True, verbose_name='Cuenta Específica'),
        ),
    ]
