# Generated by Django 2.2.4 on 2020-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0156_auto_20200302_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_aux',
            name='cuenta',
            field=models.CharField(max_length=50, null=True, verbose_name='Número Cuenta'),
        ),
    ]
