# Generated by Django 2.2.4 on 2020-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0158_auto_20200302_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cuenta_reten',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta de Retención'),
        ),
    ]
