# Generated by Django 2.2.4 on 2020-03-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0159_auto_20200302_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
