# Generated by Django 2.2.4 on 2020-03-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0160_auto_20200302_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpp_proveedor',
            options={},
        ),
    ]
