# Generated by Django 2.2.4 on 2020-03-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0162_auto_20200302_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta_arriendo_aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cuenta', models.CharField(max_length=50, null=True, verbose_name='Nombre de la Cuenta')),
                ('cuenta', models.CharField(max_length=50, null=True, verbose_name='Número de la Cuenta')),
                ('naturaleza_cuenta', models.CharField(choices=[('Credito', 'Credito'), ('Debito', 'Debito')], default='Credito', max_length=8, verbose_name='Naturaleza de la Cuenta')),
                ('arriendo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.arriendo', verbose_name='Seleccionar Arriendo')),
            ],
        ),
    ]
