# Generated by Django 2.2.4 on 2020-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0163_cuenta_arriendo_aux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='cuenta_reten',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='reten',
        ),
    ]
