# Generated by Django 2.2.4 on 2020-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0164_auto_20200302_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_arriendo',
            name='reten',
            field=models.FloatField(default=0, null=True, verbose_name='Retencion en %'),
        ),
    ]
