# Generated by Django 2.2.4 on 2020-03-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0165_cpp_arriendo_reten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_arriendo_detalle',
            name='reten',
        ),
    ]
