# Generated by Django 2.2.4 on 2020-03-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0166_remove_cpp_arriendo_detalle_reten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_arriendo_detalle',
            name='cuenta_reten',
        ),
    ]
