# Generated by Django 2.2.4 on 2020-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0167_remove_cpp_arriendo_detalle_cuenta_reten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Tarifa')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha Inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
            ],
        ),
    ]
