# Generated by Django 2.2.4 on 2020-03-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0168_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reten_383',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Tarifa', verbose_name='Nombre Tarifa'),
        ),
        migrations.AddField(
            model_name='uvt',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Tarifa', verbose_name='Nombre Tarifa'),
        ),
    ]
