# Generated by Django 2.2.4 on 2020-03-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0169_auto_20200303_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista',
            name='uvt',
        ),
        migrations.AddField(
            model_name='fac_especialista',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.Tarifa', verbose_name='Nombre Tarifa'),
        ),
    ]
