# Generated by Django 2.2.4 on 2020-03-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0170_auto_20200303_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uvt',
            name='name',
        ),
    ]
