# Generated by Django 2.2.4 on 2020-03-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0173_auto_20200313_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista_detalle',
            name='parametrizado',
        ),
    ]
