# Generated by Django 2.2.4 on 2020-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0175_fac_especialista_detalle_parametrizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_especialista_detalle',
            name='parametrizado',
            field=models.BooleanField(default=False, verbose_name='Opcion'),
        ),
    ]
