# Generated by Django 2.2.4 on 2020-04-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0181_auto_20200402_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
