# Generated by Django 2.2.4 on 2020-04-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0183_cpp_proveedor_detalle_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor_detalle',
            name='option',
            field=models.BooleanField(default=True, verbose_name='¿Parametrizado?'),
        ),
    ]
