# Generated by Django 2.2.4 on 2020-04-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0185_auto_20200404_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_especialista_detalle',
            name='parametrizado',
            field=models.BooleanField(default=True, verbose_name='¿Pamametrizado?'),
        ),
    ]
