# Generated by Django 2.2.4 on 2020-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0187_auto_20200404_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpp_proveedor',
            name='option',
            field=models.BooleanField(default=False, verbose_name='¿Parametrizado?'),
        ),
    ]
