# Generated by Django 2.2.4 on 2020-04-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0188_auto_20200404_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpp_proveedor',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.producto', verbose_name='Producto'),
        ),
    ]
