# Generated by Django 2.2.4 on 2020-04-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0189_cpp_proveedor_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor',
            name='option',
        ),
    ]
