# Generated by Django 2.2.4 on 2020-04-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0190_remove_cpp_proveedor_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpp_proveedor_detalle',
            name='option',
        ),
    ]
