# Generated by Django 2.2.4 on 2020-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0192_auto_20200406_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serv_public',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='serv_public',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='serv_public',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
