# Generated by Django 2.2.4 on 2020-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0193_auto_20200420_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='info_cont',
            field=models.TextField(blank=True, null=True, verbose_name='Información sobre el contrato'),
        ),
    ]
