# Generated by Django 2.2.4 on 2020-06-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0194_contrato_info_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='info_cont',
            new_name='info_contrato',
        ),
    ]
