# Generated by Django 2.2.4 on 2020-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0197_auto_20200610_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='especialidad',
            field=models.CharField(default='No se Registro', max_length=50, verbose_name='Especialidad'),
        ),
    ]
