# Generated by Django 2.2.4 on 2020-06-11 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0201_auto_20200611_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 6, 11, 13, 39, 35, 867807, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
