# Generated by Django 2.2.4 on 2020-06-12 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0205_auto_20200611_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro_actividad',
            name='nombre_centro_act',
            field=models.CharField(default='', max_length=70, verbose_name='Nombre Cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 6, 12, 14, 19, 39, 274969, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
