# Generated by Django 2.2.4 on 2020-06-18 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0207_auto_20200618_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 6, 18, 14, 49, 56, 529764, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='sub_activity',
            name='name_subactivity',
            field=models.CharField(max_length=70, verbose_name='Nombre de la Categoria'),
        ),
    ]
