# Generated by Django 2.2.4 on 2020-06-24 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0210_auto_20200618_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cuenta_reten',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='reten',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 19, 27, 9, 610912, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 19, 27, 9, 610912, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
