# Generated by Django 2.2.4 on 2020-06-24 19:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0211_auto_20200624_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 19, 30, 16, 464880, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 6, 24, 19, 30, 16, 464880, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='dir_prov',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='mail_prov',
            field=models.EmailField(blank=True, max_length=60, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tel_prov',
            field=models.CharField(blank=True, max_length=12, verbose_name='Telefono'),
        ),
    ]
