# Generated by Django 2.2.4 on 2020-07-06 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0213_auto_20200706_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_especialista',
            name='fecha_pagada',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 14, 12, 48, 992137, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='fechafact_esp',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 14, 12, 48, 992137, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='fac_especialista',
            name='fechafac_esp',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 14, 12, 48, 992137, tzinfo=utc), verbose_name='Fecha de Registro'),
        ),
    ]
