# Generated by Django 2.2.4 on 2020-03-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50, null=True, verbose_name='Especialidad')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, verbose_name='Nombre de la Canasta')),
                ('nombre_insumo', models.CharField(max_length=40, null=True, verbose_name='Nombre Insumo')),
                ('concepto', models.CharField(max_length=20, null=True, verbose_name='Concepto')),
                ('ubicacion', models.CharField(max_length=20, null=True, verbose_name='Ubicación')),
                ('presentacion', models.CharField(max_length=10, null=True, verbose_name='Presentación')),
                ('cantidad', models.IntegerField(default=1, null=True, verbose_name='Cantidad')),
                ('costo_und', models.FloatField(null=True, verbose_name='Costo Unitario')),
                ('costo_tot', models.FloatField(null=True, verbose_name='Costo Subtotal')),
            ],
        ),
        migrations.CreateModel(
            name='tiempo_procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_procedimiento', models.CharField(max_length=170, null=True, verbose_name='Nombre del Procedimiento')),
                ('tiempo_proc', models.FloatField(null=True, verbose_name='Tiempo del Procedimiento')),
            ],
        ),
    ]
