# Generated by Django 2.2.4 on 2020-03-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0002_auto_20200316_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_proc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20, null=True, verbose_name='Código')),
                ('nombre_proc', models.CharField(max_length=170, null=True, verbose_name='Nombre del Procedimiento')),
            ],
        ),
        migrations.AlterField(
            model_name='tiempo_procedimiento',
            name='nombre_proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Nombre del Procedimiento'),
        ),
    ]
