# Generated by Django 2.2.4 on 2020-03-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0003_auto_20200316_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_proc',
            name='nombre_proc',
        ),
        migrations.AddField(
            model_name='tipo_proc',
            name='nombre_tipo_proc',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombre del Procedimiento'),
        ),
        migrations.CreateModel(
            name='procedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proc', models.CharField(max_length=170, null=True, verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
    ]
