# Generated by Django 2.2.4 on 2020-03-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0005_auto_20200316_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concep', models.CharField(max_length=30, null=True, verbose_name='Nombre del Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='honorarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.FloatField(null=True, verbose_name='Duración')),
                ('uvr', models.FloatField(null=True, verbose_name='UVR')),
                ('info', models.TextField(null=True, verbose_name='Información')),
                ('costo', models.FloatField(null=True, verbose_name='Costo')),
                ('subtotal', models.FloatField(null=True, verbose_name='Subtotal')),
                ('canasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.canasta', verbose_name='Canasta')),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto', verbose_name='Concepto')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
    ]
