# Generated by Django 2.2.4 on 2020-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0006_concepto_honorarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto_salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_concep_sal', models.CharField(max_length=30, null=True, verbose_name='Nombre del Concepto')),
            ],
        ),
        migrations.CreateModel(
            name='constantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss_adicional', models.FloatField(null=True, verbose_name='Porcentaje Ganancia')),
            ],
        ),
        migrations.RenameModel(
            old_name='concepto',
            new_name='concepto_honorario',
        ),
        migrations.RenameField(
            model_name='concepto_honorario',
            old_name='nombre_concep',
            new_name='nombre_concep_hon',
        ),
        migrations.RenameField(
            model_name='honorarios',
            old_name='concepto',
            new_name='concepto_honorario',
        ),
    ]
