# Generated by Django 2.2.4 on 2020-03-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0007_auto_20200317_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_act', models.CharField(max_length=10, null=True, verbose_name='Presentación')),
            ],
        ),
        migrations.CreateModel(
            name='rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rubro', models.CharField(max_length=40, null=True, verbose_name='Rubro')),
            ],
        ),
        migrations.RenameModel(
            old_name='constantes',
            new_name='constante',
        ),
        migrations.RenameModel(
            old_name='honorarios',
            new_name='honorario',
        ),
        migrations.AlterField(
            model_name='concepto_salario',
            name='nombre_concep_sal',
            field=models.CharField(max_length=30, null=True, verbose_name='Concepto'),
        ),
        migrations.CreateModel(
            name='salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.FloatField(null=True, verbose_name='Duración')),
                ('costo', models.FloatField(null=True, verbose_name='Costo')),
                ('subtotal', models.FloatField(null=True, verbose_name='Subtotal')),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.actividad', verbose_name='Ubicación Actividad')),
                ('canasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.canasta', verbose_name='Canasta')),
                ('concepto_salario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto_salario', verbose_name='Concepto')),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.rubro', verbose_name='Rubro')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
    ]
