# Generated by Django 2.2.4 on 2020-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0009_auto_20200317_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='cod',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
