# Generated by Django 2.2.4 on 2020-03-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0010_auto_20200319_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto_canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, verbose_name='Nombre de la Canasta')),
            ],
        ),
        migrations.CreateModel(
            name='nombre_canasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_canasta', models.CharField(max_length=85, null=True, verbose_name='Nombre de la Canasta')),
            ],
        ),
        migrations.RemoveField(
            model_name='canasta',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='canasta',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='canasta',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='canasta',
            name='actividad',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.actividad', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='canasta',
            name='tipo_proc',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre_act',
            field=models.CharField(max_length=10, null=True, verbose_name='lugar del proceso donde se ubica'),
        ),
        migrations.AlterField(
            model_name='canasta',
            name='nombre_canasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.nombre_canasta', verbose_name='Nombre de la Canasta'),
        ),
        migrations.AlterField(
            model_name='canasta',
            name='nombre_insumo',
            field=models.CharField(max_length=60, null=True, verbose_name='Nombre Insumo'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='tipo_proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='tipo_proc',
            name='nombre_tipo_proc',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombre de la Especialidad'),
        ),
        migrations.AddField(
            model_name='canasta',
            name='concepto_canasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.concepto_canasta', verbose_name='Concepto'),
        ),
    ]
