# Generated by Django 2.2.4 on 2020-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0012_auto_20200320_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_proc',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
