# Generated by Django 2.2.4 on 2020-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0013_tipo_proc_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_proc',
            name='archivo',
            field=models.FileField(null=True, upload_to='chapters/%Y/%m/%D/'),
        ),
    ]
