# Generated by Django 2.2.4 on 2020-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0014_auto_20200324_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_proc',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='chapters/%Y/%m/%D/'),
        ),
    ]
