# Generated by Django 2.2.4 on 2020-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0016_auto_20200324_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre_proc',
            field=models.CharField(max_length=190, null=True, verbose_name='Nombre del Procedimiento'),
        ),
    ]
