# Generated by Django 2.2.4 on 2020-03-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0020_auto_20200326_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_proc',
            name='archivo',
        ),
    ]
