# Generated by Django 2.2.4 on 2020-03-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0021_remove_tipo_proc_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='tipo_proc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Especialidad'),
        ),
    ]
