# Generated by Django 2.2.4 on 2020-03-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0022_auto_20200326_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canasta',
            name='tipo_proc',
        ),
    ]
