# Generated by Django 2.2.4 on 2020-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0024_auto_20200326_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canasta',
            name='nombre_insumo',
            field=models.CharField(max_length=120, null=True, verbose_name='Nombre Insumo'),
        ),
    ]
