# Generated by Django 2.2.4 on 2020-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0026_auto_20200326_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canasta',
            name='presentacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Presentación'),
        ),
    ]
