# Generated by Django 2.2.4 on 2020-03-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0027_auto_20200326_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canasta',
            name='position',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.position', verbose_name='Ubicación'),
        ),
    ]
