# Generated by Django 2.2.4 on 2020-03-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0030_auto_20200326_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='uvr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='UVR'),
        ),
    ]
