# Generated by Django 2.2.4 on 2020-03-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0031_auto_20200326_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimiento',
            options={},
        ),
    ]
