# Generated by Django 2.2.4 on 2020-03-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0033_auto_20200326_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorario',
            name='duracion',
        ),
    ]
