# Generated by Django 2.2.4 on 2020-03-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0035_remove_honorario_uvr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorario',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='subtotal',
        ),
    ]
