# Generated by Django 2.2.4 on 2020-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0036_auto_20200330_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='costo',
            field=models.FloatField(null=True, verbose_name='Costo no Paramertrizado'),
        ),
    ]
