# Generated by Django 2.2.4 on 2020-03-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0037_honorario_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='costo',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo no Paramertrizado'),
        ),
    ]
