# Generated by Django 2.2.4 on 2020-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0038_auto_20200330_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='costo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Costo no Paramertrizado'),
        ),
    ]
