# Generated by Django 2.2.4 on 2020-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0039_auto_20200330_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='valor_uvt',
            field=models.FloatField(default=0, null=True, verbose_name='Valor UVT Especialistas'),
        ),
    ]
