# Generated by Django 2.2.4 on 2020-03-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0040_constante_valor_uvt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='canasta',
        ),
        migrations.AddField(
            model_name='salario',
            name='nombre_canasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.nombre_canasta', verbose_name='Canasta'),
        ),
    ]
