# Generated by Django 2.2.4 on 2020-03-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0042_remove_salario_rubro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimiento',
            options={},
        ),
    ]
