# Generated by Django 2.2.4 on 2020-03-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0043_auto_20200331_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='nombre_canasta',
        ),
    ]
