# Generated by Django 2.2.4 on 2020-03-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0044_remove_salario_nombre_canasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento'),
        ),
    ]
