# Generated by Django 2.2.4 on 2020-03-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0045_salario_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.position', verbose_name='Ubicación Concepto'),
        ),
    ]
