# Generated by Django 2.2.4 on 2020-04-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0046_auto_20200331_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='subtotal',
        ),
    ]
