# Generated by Django 2.2.4 on 2020-05-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0047_auto_20200401_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.procedimiento', verbose_name='Nombre del Procedimiento')),
                ('tipo_proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cirugia.tipo_proc', verbose_name='Tipo Procedimiento')),
            ],
        ),
    ]
