# Generated by Django 2.2.4 on 2020-05-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0048_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_canasta',
            name='nombre_canasta',
            field=models.CharField(max_length=85, null=True, verbose_name='Concepto de la Canasta'),
        ),
    ]
