# Generated by Django 2.2.4 on 2020-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0049_auto_20200518_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ganancia',
            field=models.FloatField(default=0, verbose_name='Ganancia'),
        ),
    ]
