# Generated by Django 2.2.4 on 2020-05-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0051_auto_20200528_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rubro',
        ),
    ]
