# Generated by Django 2.2.4 on 2020-05-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0053_estancia_tipo_estancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_estancia',
            name='dividir_por_cama',
            field=models.BooleanField(default=True, verbose_name='¿Se divide entre el número de camas ?'),
        ),
    ]
