# Generated by Django 2.2.4 on 2020-05-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0054_tipo_estancia_dividir_por_cama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_estancia',
            name='dividir_por_cama',
        ),
        migrations.AddField(
            model_name='estancia',
            name='dividir_por_cama',
            field=models.BooleanField(default=True, verbose_name='¿Se divide entre el número de camas ?'),
        ),
    ]
