# Generated by Django 2.2.4 on 2020-05-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0055_auto_20200529_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='duracion_proc',
            field=models.FloatField(null=True, verbose_name='Duración en minutos'),
        ),
    ]
