# Generated by Django 2.2.4 on 2020-05-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirugia', '0056_auto_20200529_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='dias_estancia',
            field=models.IntegerField(default=0, null=True, verbose_name='Días Estancia'),
        ),
    ]
